### ISSUE TITLE
any benchmark?

### ISSUE THREAD

**Issue by i5ting** [magicdawn/impress-router#1]

**Comment by magicdawn** [comment]
Not yet. 

I'm not able to find out which koa router implementation has got bench. So let me see.

**Comment by fundon** [comment]
https://github.com/trekjs/router

**Comment by magicdawn** [comment]
That's a router bench to find out the right handler, seems that this do not provide `find handler`. 
It's a express router port version for koa, and it's using `path-to-regexp` which express is using. 

Maybe we can bench the whole request pipe line.

**Comment by fundon** [comment]
@magicdawn `trek-router` has support `#find()` API.

See example: https://github.com/trekjs/router#usage

**Comment by magicdawn** [comment]
> That's a router bench to find out the right handler, seems that this do not provide find handler

你的测试是根据request path 找出正确的handler, 但是这个没有这个功能, 没有 `find` , 要一起bench , 只能走完整 HTTP request. 
see https://github.com/magicdawn/impress-router-benchmark/blob/master/index.js

**Comment by fundon** [comment]
是的，只匹配正确到的 `path` 即可

**Comment by magicdawn** [comment]
Sorry. 我不想 test driven develop. I'm closing it.
BTW apiGithub & apiDiscourse cost 700+ms / cycle.
