### ISSUE TITLE
Regarding query params in impress router

### ISSUE THREAD

**Issue by pintoo81** [magicdawn/impress-router#15]
Would like to know, 
1. how to pass query params in impress router
2. how to fetch that query param value

**Comment by magicdawn** [comment]
is this http://expressjs.com/en/4x/api.html#router.param what you are saying?
I never use that, I believe get the `id` and manual fetch user feels more clear. So it's not supported for now.

**Comment by magicdawn** [comment]
or u mean querystring params, just use `ctx.query`
